export const bodyPartLabels: Record<string, string> = {
  anterior_head: "Tête (ant.)",
  anterior_neck_left: "Cou (G)",
  anterior_neck_right: "Cou (D)",
  trapezius_left: "Trapèze gauche",
  trapezius_right: "Trapèze droit",
  anterior_shoulder_left: "Épaule gauche (ant.)",
  anterior_shoulder_right: "Épaule droite (ant.)",
  anterior_biceps_left: "Biceps gauche",
  anterior_biceps_right: "Biceps droit",
  anterior_elbow_left: "Coude gauche (ant.)",
  anterior_elbow_right: "Coude droit (ant.)",
  anterior_forearm_left: "Avant-bras gauche (ant.) (fléchisseurs)",
  anterior_forearm_right: "Avant-bras droit (ant.) (fléchisseurs)",
  anterior_wrist_left: "Poignet gauche (ant.)",
  anterior_wrist_right: "Poignet droit (ant.)",
  anterior_hand_left: "Main gauche (ant.) (face palmaire)",
  anterior_hand_right: "Main droite (ant.) (face palmaire)",
  pectoral_left: "Pectoral gauche",
  pectoral_right: "Pectoral droit",
  ribs_left: "Côtes gauches",
  ribs_right: "Côtes droites",
  abdominals_left: "Adbominaux gauches",
  abdominals_right: "Abdominaux droits",
  obliques_left: "Obliques gauches",
  obliques_right: "Obliques droits",
  hip_left: "Hanche gauche",
  hip_right: "Hanche droite",
  quadriceps_left: "Quadriceps gauche",
  quadriceps_right: "Quadriceps droit",
  adductor_left: "Adducteur gauche",
  adductor_right: "Adducteur droit",
  anterior_knee_left: "Genou gauche (ant.)",
  anterior_knee_right: "Genou droit (ant.)",
  tibia_left: "Tibia gauche",
  tibia_right: "Tibia droit",
  anterior_ankle_left: "Cheville gauche (ant.)",
  anterior_ankle_right: "Cheville droite (ant.)",
  anterior_foot_left: "Pied gauche",
  anterior_foot_right: "Pied droit",
  posterior_head: "Tête (post.)",
  posterior_shoulder_left: "Epaule gauche (post.)",
  posterior_shoulder_right: "Epaule droite (post.)",
  triceps_left: "Triceps gauche",
  triceps_right: "Triceps droit",
  posterior_elbow_left: "Coude gauche (post.)",
  posterior_elbow_right: "Coude droit (post.)",
  posterior_forearm_left: "Avant-bras gauche (post.) (extenseurs)",
  posterior_forearm_right: "Avant-bras droit (post.) (extenseurs)",
  posterior_wrist_left: "Poignet gauche (post.)",
  posterior_wrist_right: "Poignet droit (post.)",
  posterior_hand_left: "Main gauche (post.) (face dorsale)",
  posterior_hand_right: "Main droit (post.) (face dorsale)",
  spine: "Colonne vertébrale",
  scapular_left: "Région scapulaire gauche",
  scapular_right: "Région scapulaire droite",
  back_flank_left: "Dos (flanc gauche)",
  back_flank_right: "Dos (flanc droit)",
  lumbar_left: "Lombaire gauche",
  lumbar_right: "Lombaire droit",
  buttock_left: "Fesse gauche",
  buttock_right: "Fesse droite",
  hamstrings_left: "Ischios gauches",
  hamstrings_right: "Ischios droits",
  posterior_knee_left: "Genou gauche (post.)",
  posterior_knee_right: "Genou droit (post.)",
  calf_left: "Mollet gauche",
  calf_right: "Mollet droit",
  posterior_ankle_left: "Cheville gauche (post.)",
  posterior_ankle_right: "Chevile droite (post.)",
  posterior_foot_left: "Pied gauche (post.)",
  posterior_foot_right: "Pied droit (post.)",
}

export const bodyChartLegacyLabelToId: Record<string, string> = {
  "Tête (ant.)": "anterior_head",
  "Cou (G)": "anterior_neck_left",
  "Cou (D)": "anterior_neck_right",
  "Trapèze gauche": "trapezius_left",
  "Trapèze droit": "trapezius_right",
  "Épaule gauche (ant.)": "anterior_shoulder_left",
  "Épaule droite (ant.)": "anterior_shoulder_right",
  "Biceps gauche": "anterior_biceps_left",
  "Biceps droit": "anterior_biceps_right",
  "Coude gauche (ant.)": "anterior_elbow_left",
  "Coude droit (ant.)": "anterior_elbow_right",
  "Avant-bras gauche (ant.) (fléchisseurs)": "anterior_forearm_left",
  "Avant-bras droit (ant.) (fléchisseurs)": "anterior_forearm_right",
  "Poignet gauche (ant.)": "anterior_wrist_left",
  "Poignet droit (ant.)": "anterior_wrist_right",
  "Main gauche (ant.) (face palmaire)": "anterior_hand_left",
  "Main droite (ant.) (face palmaire)": "anterior_hand_right",
  "Pectoral gauche": "pectoral_left",
  "Pectoral droit": "pectoral_right",
  "Côtes gauches": "ribs_left",
  "Côtes droites": "ribs_right",
  "Adbominaux gauches": "abdominals_left",
  "Abdominaux droits": "abdominals_right",
  "Obliques gauches": "obliques_left",
  "Obliques droits": "obliques_right",
  "Hanche gauche": "hip_left",
  "Hanche droite": "hip_right",
  "Quadriceps gauche": "quadriceps_left",
  "Quadriceps droit": "quadriceps_right",
  "Adducteur gauche": "adductor_left",
  "Adducteur droit": "adductor_right",
  "Genou gauche (ant.)": "anterior_knee_left",
  "Genou droit (ant.)": "anterior_knee_right",
  "Tibia gauche": "tibia_left",
  "Tibia droit": "tibia_right",
  "Cheville gauche (ant.)": "anterior_ankle_left",
  "Cheville droite (ant.)": "anterior_ankle_right",
  "Pied gauche": "anterior_foot_left",
  "Pied droit": "anterior_foot_right",
  "Tête (post.)": "posterior_head",
  "Epaule gauche (post.)": "posterior_shoulder_left",
  "Epaule droite (post.)": "posterior_shoulder_right",
  "Triceps gauche": "triceps_left",
  "Triceps droit": "triceps_right",
  "Coude gauche (post.)": "posterior_elbow_left",
  "Coude droit (post.)": "posterior_elbow_right",
  "Avant-bras gauche (post.) (extenseurs)": "posterior_forearm_left",
  "Avant-bras droit (post.) (extenseurs)": "posterior_forearm_right",
  "Poignet gauche (post.)": "posterior_wrist_left",
  "Poignet droit (post.)": "posterior_wrist_right",
  "Main gauche (post.) (face dorsale)": "posterior_hand_left",
  "Main droit (post.) (face dorsale)": "posterior_hand_right",
  "Colonne vertébrale": "spine",
  "Région scapulaire gauche": "scapular_left",
  "Région scapulaire droite": "scapular_right",
  "Dos (flanc gauche)": "back_flank_left",
  "Dos (flanc droit)": "back_flank_right",
  "Lombaire gauche": "lumbar_left",
  "Lombaire droit": "lumbar_right",
  "Fesse gauche": "buttock_left",
  "Fesse droite": "buttock_right",
  "Ischios gauches": "hamstrings_left",
  "Ischios droits": "hamstrings_right",
  "Genou gauche (post.)": "posterior_knee_left",
  "Genou droit (post.)": "posterior_knee_right",
  "Mollet gauche": "calf_left",
  "Mollet droit": "calf_right",
  "Cheville gauche (post.)": "posterior_ankle_left",
  "Chevile droite (post.)": "posterior_ankle_right",
  "Pied gauche (post.)": "posterior_foot_left",
  "Pied droit (post.)": "posterior_foot_right",
}

export function normalizeBodyChartPartId(part: string) {
  const normalizedPart = part.trim()

  if (normalizedPart in bodyPartLabels) {
    return normalizedPart
  }

  return bodyChartLegacyLabelToId[normalizedPart] ?? normalizedPart
}

export function normalizeBodyChartPartIds(parts: string[]) {
  return [...new Set(parts.map(normalizeBodyChartPartId))]
}
