// Labels des parties du corps pour le schéma ostéopathe
export const bodyPartLabels: Record<string, string> = {
    // Antérieur
    "tete": "Tête",
    "couG": "Cou (G)",
    "couD": "Cou (D)",
    "trapG": "Trapèze gauche",
    "trapD": "Trapèze droit",
    "epG": "Épaule gauche",
    "epD": "Épaule droite",
    "biG": "Biceps gauche",
    "biD": "Biceps droit",
    "coudG": "Coude gauche",
    "coudD": "Coude droit",
    "avbG": "Avant-bras gauche",
    "avbD": "Avant-bras droit",
    "poiG": "Poignet gauche",
    "poiD": "Poignet droit",
    "mainG": "Main gauche",
    "mainD": "Main droite",
    "pecG": "Pectoral gauche",
    "pecD": "Pectoral droit",
    "cotG": "Côtes gauches",
    "cotD": "Côtes droites",
    "abdG": "Abdominaux gauches",
    "abdD": "Abdominaux droits",
    "oblG": "Obliques gauches",
    "oblD": "Obliques droits",
    "hanG": "Hanche gauche",
    "hanD": "Hanche droite",
    "quadG": "Quadriceps gauche",
    "quadD": "Quadriceps droit",
    "addG": "Adducteur gauche",
    "addD": "Adducteur droit",
    "genG": "Genou gauche",
    "genD": "Genou droit",
    "tibG": "Tibia gauche",
    "tibD": "Tibia droit",
    "cheG": "Cheville gauche",
    "cheD": "Cheville droite",
    "pieG": "Pied gauche",
    "pieD": "Pied droit",

    // Postérieur
    "triG": "Triceps gauche",
    "triD": "Triceps droit",
    "col": "Colonne vertébrale",
    "scaG": "Région scapulaire gauche",
    "scaD": "Région scapulaire droite",
    "dosG": "Dos (flanc gauche)",
    "dosD": "Dos (flanc droit)",
    "lombG": "Lombaire gauche",
    "lombD": "Lombaire droit",
    "fesG": "Fesse gauche",
    "fesD": "Fesse droite",
    "iscG": "Ischios gauches",
    "iscD": "Ischios droits",
    "molG": "Mollet gauche",
    "molD": "Mollet droit",
}
